<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>RestreamTestRunner</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.6.1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RestreamChatPlugin.Tests">
      <HintPath>..\RestreamChatPlugin.Tests\bin\Debug\net48\RestreamChatPlugin.Tests.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
